name: Build and Create JAR

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
                 java-version: '17'
                 distribution: 'adopt'
                 cache: maven


        - name: cache maven dependencies
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}gi
          
        - name: Build with Maven
          run: mvn clean install
        
        - name: create jar files
          uses: actions/upload-artifact@v4
          with:
            name: jar
            path: target/*.jar
        
        - name: Configure JFrog CLI
          uses: jfrog/setup-jfrog-cli@v3
          with:
                version: latest
          env: 
            JF_URL: https://trial1dnxmv.jfrog.io
            JF_ACCESS_TOKEN: ${{ secrets.JFROG }}
        
        - name: Upload to JFrog
          run:  jf rt u "target/*.jar" "petclinicrepo/" --build-name="petclinic" --build-number=${{ github.run_number }}
          

        # - name: Create JAR file
        #   run: ./gradlew jar

        # - name: Upload JAR file
        #   uses: actions/upload-artifact@v3
        #   with:
        #         name: my-app
        #         path: build/libs/*.jar
