name: Build and Create JAR

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
                 java-version: '17'
                 distribution: 'adopt'

        # - name: Build with Gradle
        #   run: ./gradlew build

        # - name: Create JAR file
        #   run: ./gradlew jar

        # - name: Upload JAR file
        #   uses: actions/upload-artifact@v3
        #   with:
        #         name: my-app
        #         path: build/libs/*.jar
