name: CI Pipeline Feature
on:
  push:
    branches:
      - main 

jobs:
  build:
    uses: ./.github/workflows/buildcode.yml
    secrets: inherit
  sonar:
     uses: ./.github/workflows/sonar.yml
     needs: build
     secrets: inherit   
  
  image:
    uses: ./.github/workflows/image.yml
    needs: build
    secrets: inherit
